const LEVELS=[
{id:'easy',name:'Fácil',cls:'easy',games:[
{letters:'CASA',words:['CASA','ASA']},{letters:'GATO',words:['GATO','GOTA','ATO']},{letters:'PATO',words:['PATO','TOPA','ATO']},{letters:'MALA',words:['MALA','ALMA','LAMA']},{letters:'RATO',words:['RATO','ROTA','ATO']},{letters:'LAGO',words:['LAGO','GALO','ALGO']},{letters:'PENA',words:['PENA','PANE']},{letters:'RICO',words:['RICO','COR','RIO']},{letters:'FARO',words:['FARO','FORA']},{letters:'VIDA',words:['VIDA','VIA','DIA']}]},
{id:'medium',name:'Médio',cls:'medium',games:[
{letters:'AMIGO',words:['AMIGO','GOMA']},{letters:'CLARO',words:['CLARO','CALOR','ORAL']},{letters:'PEDRA',words:['PEDRA','PARE']},{letters:'PRATO',words:['PRATO','PORTA','RATO']},{letters:'LIVRO',words:['LIVRO','VIRO','RIO']},{letters:'MORAL',words:['MORAL','AMOR','RAMO']},{letters:'FESTA',words:['FESTA','SETA']},{letters:'NORTE',words:['NORTE','TERNO']},{letters:'GRATO',words:['GRATO','GATO','RATO']},{letters:'BANCO',words:['BANCO','BOCA']}]},
{id:'hard',name:'Difícil',cls:'hard',games:[
{letters:'MÚSICA',words:['MÚSICA','CISMA']},{letters:'POLÍCIA',words:['POLÍCIA','COPIA']},{letters:'CIDADE',words:['CIDADE','DICA','IDEIA']},{letters:'ESCOLA',words:['ESCOLA','COLA','SECO']},{letters:'JANELA',words:['JANELA','ANEL']},{letters:'CORAGEM',words:['CORAGEM','AMOR','GEMA']},{letters:'BELEZA',words:['BELEZA','ELA']},{letters:'CAMINHO',words:['CAMINHO','MINHA']},{letters:'PLANETA',words:['PLANETA','PLENA']},{letters:'CADERNO',words:['CADERNO','CEDRO']}]},
{id:'xhard',name:'Extra Difícil',cls:'xhard',games:[
{letters:'LIBERDADE',words:['LIBERDADE','IDADE','REAL']},{letters:'CRIATIVO',words:['CRIATIVO','ATIVO']},{letters:'NATUREZA',words:['NATUREZA','NEUTRA','AZAR']},{letters:'ENERGIA',words:['ENERGIA','AREIA','GIRA']},{letters:'MEMORIA',words:['MEMORIA','AMOR','MIMO']},{letters:'PALAVRA',words:['PALAVRA','LAVA','PAR']},{letters:'CAMINHAR',words:['CAMINHAR','MARCA','RIMA']},{letters:'FUTURO',words:['FUTURO','FRUTO','OURO']},{letters:'CULTURA',words:['CULTURA','CURTA','LUTA']},{letters:'VIBRANTE',words:['VIBRANTE','BRINCAR','VIBRAR']}]}
];
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const count=s=>[...norm(s)].reduce((m,c)=>(m[c]=(m[c]||0)+1,m),{});
function canBuild(word,letters){const a=count(word),b=count(letters);return Object.keys(a).every(k=>a[k]<=(b[k]||0))}
function validateAll(){const errors=[];LEVELS.forEach((l,li)=>l.games.forEach((g,gi)=>{g.words.forEach(w=>{if(!canBuild(w,g.letters))errors.push(`${l.name} ${gi+1}: ${w} não cabe em ${g.letters}`);if(/[ÃÕÂÊÔÇ]/i.test(w))errors.push(`${l.name} ${gi+1}: caractere bloqueado em ${w}`)})}));if(errors.length)console.error('Erros de conteúdo Palaviva',errors)}
validateAll();
let state=JSON.parse(localStorage.getItem('palaviva-state-v2')||'{"level":0,"match":0,"unlocked":0,"completed":{}}');
const app=document.querySelector('#app');
function save(){localStorage.setItem('palaviva-state-v2',JSON.stringify(state))}
function menu(){app.innerHTML=`<main class="app"><div class="top"><div class="brand">palaviva.</div><div class="pill">40 partidas · sem anúncios</div></div><section class="hero"><h1>Encontre.<br>Conecte. Avance.</h1><p>Português do Brasil, quatro níveis e um final de verdade.</p></section><section class="levels">${LEVELS.map((l,i)=>{let locked=i>state.unlocked,done=Object.keys(state.completed).filter(k=>k.startsWith(i+'-')).length;return `<button class="level ${l.cls} ${locked?'locked':''}" ${locked?'disabled':''} onclick="startLevel(${i})"><small>${locked?'🔒':done+'/10'}</small><h2>${l.name}</h2><p>${locked?'Complete o nível anterior':done===10?'Concluído · jogar novamente':done?'Continuar campanha':'Começar'}</p></button>`}).join('')}</section></main>`}
window.startLevel=i=>{let done=Object.keys(state.completed).filter(k=>k.startsWith(i+'-')).map(k=>+k.split('-')[1]);let m=done.length===10?0:(done.length?Math.max(...done)+1:0);play(i,Math.min(m,9))}
function buildCrossword(words){
 const W=19,H=19, grid=Array.from({length:H},()=>Array(W).fill(null)), placements=[];
 const sorted=[...words].sort((a,b)=>norm(b).length-norm(a).length);
 const first=norm(sorted.shift()), r0=9,c0=Math.floor((W-first.length)/2); [...first].forEach((ch,i)=>grid[r0][c0+i]=ch);placements.push({word:first,r:r0,c:c0,dir:'h'});
 function fits(word,r,c,dir){let crosses=0;for(let i=0;i<word.length;i++){let rr=r+(dir==='v'?i:0),cc=c+(dir==='h'?i:0);if(rr<0||cc<0||rr>=H||cc>=W)return -1;let ex=grid[rr][cc];if(ex&&ex!==word[i])return -1;if(ex===word[i])crosses++;if(!ex){if(dir==='h'){if((rr>0&&grid[rr-1][cc])||(rr<H-1&&grid[rr+1][cc]))return -1}else{if((cc>0&&grid[rr][cc-1])||(cc<W-1&&grid[rr][cc+1]))return -1}}}let br=r-(dir==='v'),bc=c-(dir==='h'),ar=r+(dir==='v'?word.length:0),ac=c+(dir==='h'?word.length:0);if(br>=0&&bc>=0&&br<H&&bc<W&&grid[br][bc])return -1;if(ar>=0&&ac>=0&&ar<H&&ac<W&&grid[ar][ac])return -1;return crosses}
 for(const raw of sorted){const word=norm(raw);let best=null;for(let wi=0;wi<word.length;wi++)for(let r=0;r<H;r++)for(let c=0;c<W;c++)if(grid[r][c]===word[wi]){for(const dir of ['h','v']){let sr=r-(dir==='v'?wi:0),sc=c-(dir==='h'?wi:0),score=fits(word,sr,sc,dir);if(score>0&&(!best||score>best.score))best={r:sr,c:sc,dir,score}}}if(!best){console.warn('Sem cruzamento para',word);continue;}[...word].forEach((ch,i)=>grid[best.r+(best.dir==='v'?i:0)][best.c+(best.dir==='h'?i:0)]=ch);placements.push({word,...best});}
 let cells=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)if(grid[r][c])cells.push({r,c,ch:grid[r][c]});let minR=Math.min(...cells.map(x=>x.r)),maxR=Math.max(...cells.map(x=>x.r)),minC=Math.min(...cells.map(x=>x.c)),maxC=Math.max(...cells.map(x=>x.c));return {cells,placements,minR,maxR,minC,maxC};
}
function play(li,mi){state.level=li;state.match=mi;save();const level=LEVELS[li],game=level.games[mi],words=game.words,layout=buildCrossword(words);let found=new Set(),revealed=new Set(),order=[...norm(game.letters)];render();
 function key(r,c){return r+'-'+c}
 function render(){let rows=layout.maxR-layout.minR+1,cols=layout.maxC-layout.minC+1;app.innerHTML=`<main class="app game ${level.cls}"><div class="gamehead"><button class="back" id="back">‹ Menu</button><div class="game-title"><strong>${level.name}</strong><span>Partida ${mi+1} de 10</span></div><button class="iconbtn" id="reset">↻</button></div><div class="progress">${Array.from({length:10},(_,i)=>`<i class="dot ${i<mi?'done':i===mi?'now':''}"></i>`).join('')}</div><section class="board"><div class="crossword" style="--rows:${rows};--cols:${cols}">${layout.cells.map(cell=>{let visible=revealed.has(key(cell.r,cell.c));return `<span class="cell ${visible?'revealed':''}" style="grid-row:${cell.r-layout.minR+1};grid-column:${cell.c-layout.minC+1}">${visible?displayChar(cell.ch,words):''}</span>`}).join('')}</div></section><section class="wheel-wrap"><div class="current" id="current"></div><div class="wheel" id="wheel"></div><div class="actions"><button class="action" id="shuffle">⤨ Embaralhar</button><button class="action" id="hint">💡 Dica</button></div></section></main>`;document.querySelector('#back').onclick=menu;document.querySelector('#reset').onclick=()=>play(li,mi);document.querySelector('#shuffle').onclick=()=>{order.sort(()=>Math.random()-.5);drawWheel()};document.querySelector('#hint').onclick=hint;drawWheel()}
 function displayChar(ch){for(const w of words){const nw=norm(w);for(let i=0;i<nw.length;i++)if(nw[i]===ch&&w[i]&&norm(w[i])===ch)return w[i].toUpperCase()}return ch}
 function revealWord(raw){let p=layout.placements.find(p=>p.word===norm(raw));if(!p)return;for(let i=0;i<p.word.length;i++)revealed.add(key(p.r+(p.dir==='v'?i:0),p.c+(p.dir==='h'?i:0)))}
 function hint(){let target=words.find(w=>!found.has(w));if(!target)return;let p=layout.placements.find(p=>p.word===norm(target));for(let i=0;i<p.word.length;i++){let k=key(p.r+(p.dir==='v'?i:0),p.c+(p.dir==='h'?i:0));if(!revealed.has(k)){revealed.add(k);toast('Uma letra foi revelada');render();return}}}
 function drawWheel(){const wheel=document.querySelector('#wheel');wheel.innerHTML='';order.forEach((ch,i)=>{let a=(i/order.length)*Math.PI*2-Math.PI/2,r=38,x=50+Math.cos(a)*r,y=50+Math.sin(a)*r;let b=document.createElement('div');b.className='letter';b.textContent=ch;b.dataset.i=i;b.style.left=x+'%';b.style.top=y+'%';wheel.appendChild(b)});bindWheel(wheel)}
 function bindWheel(wheel){let active=false,sel=[],els=[];const pick=e=>{let p=e.touches?e.touches[0]:e,el=document.elementFromPoint(p.clientX,p.clientY);if(el?.classList.contains('letter')){let i=+el.dataset.i;if(!sel.includes(i)){sel.push(i);els.push(el);el.classList.add('active');document.querySelector('#current').textContent=sel.map(j=>order[j]).join('')}}};const begin=e=>{active=true;sel=[];els=[];pick(e)};const move=e=>{if(active){e.preventDefault();pick(e)}};const end=()=>{if(!active)return;active=false;let attempt=sel.map(j=>order[j]).join('');els.forEach(x=>x.classList.remove('active'));let hit=words.find(w=>norm(w)===attempt);if(hit&&!found.has(hit)){found.add(hit);revealWord(hit);toast(hit.toUpperCase());if(found.size===words.length){state.completed[li+'-'+mi]=true;save();render();setTimeout(()=>complete(li,mi),500)}else render()}else if(attempt.length>1)toast('Tente outra combinação');let cur=document.querySelector('#current');if(cur)cur.textContent=''};wheel.onpointerdown=begin;wheel.onpointermove=move;window.onpointerup=end;wheel.ontouchstart=begin;wheel.ontouchmove=move;window.ontouchend=end}
}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),900)}
function complete(li,mi){confetti();let levelEnd=mi===9,gameEnd=levelEnd&&li===3;if(levelEnd&&li<3)state.unlocked=Math.max(state.unlocked,li+1);save();let o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="card"><div class="big">${gameEnd?'🏆':levelEnd?'⚡':'✨'}</div><h2>${gameEnd?'Você venceu!':levelEnd?LEVELS[li].name+' concluído!':'Partida concluída!'}</h2><p>${gameEnd?'As 40 partidas foram concluídas. Você zerou o Palaviva.':levelEnd&&li<3?LEVELS[li+1].name+' foi desbloqueado.':'Pronta para a próxima partida?'}</p><button class="primary">${gameEnd?'Voltar ao menu':'Continuar'}</button></div>`;document.body.appendChild(o);o.querySelector('button').onclick=()=>{o.remove();if(gameEnd)return menu();if(levelEnd)return play(li+1,0);play(li,mi+1)}}
function confetti(){let c=document.createElement('div');c.className='confetti';for(let i=0;i<55;i++){let x=document.createElement('i');x.style.left=Math.random()*100+'%';x.style.setProperty('--h',Math.random()*360);x.style.setProperty('--x',(Math.random()*180-90)+'px');x.style.animationDelay=Math.random()*.4+'s';c.appendChild(x)}document.body.appendChild(c);setTimeout(()=>c.remove(),2200)}
menu();
