const LEVELS=[
 {id:'easy',name:'Fácil',cls:'easy',sets:[['CASA','MESA','CAMA'],['GATO','PATO','TOCA'],['BOLA','BOLO','LOBO'],['VIDA','DIA','VIA'],['RATO','ATO','ROTA'],['MALA','ALMA','LAMA'],['JOGO','FOGO'],['LAGO','GALO','ALGO'],['PENA','PANO','ANO'],['RICO','COR','RIO']]},
 {id:'medium',name:'Médio',cls:'medium',sets:[['AMIGO','MAGIA','GOMA'],['JOVEM','MOVE','VEJO'],['CLARO','CALOR','ORAL'],['FALAR','FALA','LAR'],['PAPEL','PELA'],['PEDRA','PARE','REDE'],['PRATO','PORTA','RATO'],['LIVRO','VIRO','RIO'],['MORAL','AMOR','RAMO'],['FESTA','ESTA','SETA']]},
 {id:'hard',name:'Difícil',cls:'hard',sets:[['MÚSICA','CISMA','UMA'],['POLÍCIA','COPIA','PICA'],['ÁGUA'],['CIDADE','IDEIA','DICA'],['ESCOLA','COLA','SECO'],['TRABALHO','BARALHO','OLHAR'],['JANELA','ANEL','LENA'],['CAMINHO','MINHA'],['CORAGEM','AMOR','GEMA'],['BELEZA','ZEBRA','ELA']]},
 {id:'xhard',name:'Extra Difícil',cls:'xhard',sets:[['LIBERDADE','IDADE','REAL'],['CRIATIVO','ATIVO'],['NATUREZA','NEUTRA','AZAR'],['ENERGIA','AREIA','GIRA'],['MEMORIA','AMOR','MIMO'],['PALAVRA','LAVA','PAR'],['CAMINHAR','MARCA','RIMA'],['FUTURO','FRUTO','OURO'],['CULTURA','CURTA','LUTA'],['VIBRANTE','BRINCA']]}
];
// Curadoria preliminar: a arquitetura aceita trocar qualquer partida sem tocar no motor.
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const valid=s=>!/[ÃÕÂÊÔÇ]/i.test(s);
let state=JSON.parse(localStorage.getItem('palaviva-state')||'{"level":0,"match":0,"unlocked":0,"completed":{}}');
const app=document.querySelector('#app');
function save(){localStorage.setItem('palaviva-state',JSON.stringify(state))}
function menu(){app.innerHTML=`<main class="app"><div class="top"><div class="brand">palaviva.</div><div class="pill">40 partidas · sem anúncios</div></div><section class="hero"><h1>Encontre.<br>Conecte. Avance.</h1><p>Português do Brasil, quatro níveis e um final de verdade.</p></section><section class="levels">${LEVELS.map((l,i)=>{let locked=i>state.unlocked,done=Object.keys(state.completed).filter(k=>k.startsWith(i+'-')).length;return `<button class="level ${l.cls} ${locked?'locked':''}" ${locked?'disabled':''} onclick="startLevel(${i})"><small>${locked?'🔒':done+'/10'}</small><h2>${l.name}</h2><p>${locked?'Complete o nível anterior':done===10?'Concluído · jogar novamente':done?'Continuar campanha':'Começar'}</p></button>`}).join('')}</section></main>`}
window.startLevel=i=>{let done=Object.keys(state.completed).filter(k=>k.startsWith(i+'-')).map(k=>+k.split('-')[1]);let m=done.length===10?0:Math.max(0,...done.map(x=>x+1)); if(done.length===0)m=0; play(i,Math.min(m,9))}
function lettersFor(words){let longest=[...words].sort((a,b)=>norm(b).length-norm(a).length)[0];return [...norm(longest)]}
function play(li,mi){state.level=li;state.match=mi;save();const level=LEVELS[li], words=level.sets[mi].filter(valid), letters=lettersFor(words);let found=new Set();let order=[...letters];render();function render(){app.innerHTML=`<main class="app game"><div class="gamehead"><button class="back" id="back">‹ Menu</button><div class="game-title"><strong>${level.name}</strong><span>Partida ${mi+1} de 10</span></div><button class="iconbtn" id="reset">↻</button></div><div class="progress">${Array.from({length:10},(_,i)=>`<i class="dot ${i<mi?'done':i===mi?'now':''}"></i>`).join('')}</div><section class="board"><div class="words">${words.map(w=>`<div class="wordrow">${[...w].map(ch=>`<span class="cell ${found.has(w)?'':'hidden'}">${ch}</span>`).join('')}</div>`).join('')}</div></section><section class="wheel-wrap"><div class="current" id="current"></div><div class="wheel" id="wheel"></div><div class="actions"><button class="action" id="shuffle">⤨ Embaralhar</button><button class="action" id="hint">💡 Dica</button></div></section></main>`;document.querySelector('#back').onclick=menu;document.querySelector('#reset').onclick=()=>play(li,mi);document.querySelector('#shuffle').onclick=()=>{order.sort(()=>Math.random()-.5);drawWheel()};document.querySelector('#hint').onclick=()=>{let w=words.find(w=>!found.has(w));if(w)toast(`Dica: começa com ${w[0]} e tem ${norm(w).length} letras`)};drawWheel()}
 function drawWheel(){const wheel=document.querySelector('#wheel');wheel.innerHTML='';order.forEach((ch,i)=>{let a=(i/order.length)*Math.PI*2-Math.PI/2,r=82,x=130+Math.cos(a)*r,y=130+Math.sin(a)*r;let b=document.createElement('div');b.className='letter';b.textContent=ch;b.dataset.i=i;b.style.left=x/260*100+'%';b.style.top=y/260*100+'%';wheel.appendChild(b)});bindWheel(wheel)}
 function bindWheel(wheel){let active=false,sel=[],els=[];const pick=e=>{let p=e.touches?e.touches[0]:e;let el=document.elementFromPoint(p.clientX,p.clientY);if(el?.classList.contains('letter')){let i=+el.dataset.i;if(!sel.includes(i)){sel.push(i);els.push(el);el.classList.add('active');document.querySelector('#current').textContent=sel.map(j=>order[j]).join('')}}};const begin=e=>{active=true;sel=[];els=[];pick(e)};const move=e=>{if(active){e.preventDefault();pick(e)}};const end=()=>{if(!active)return;active=false;let attempt=sel.map(j=>order[j]).join('');els.forEach(x=>x.classList.remove('active'));let hit=words.find(w=>norm(w)===attempt);if(hit&&!found.has(hit)){found.add(hit);toast(hit);if(found.size===words.length){state.completed[li+'-'+mi]=true;save();setTimeout(()=>complete(li,mi),350)}else render()}else if(attempt.length>1)toast('Tente outra combinação');document.querySelector('#current')&&(document.querySelector('#current').textContent='')};wheel.onpointerdown=begin;wheel.onpointermove=move;window.onpointerup=end;wheel.ontouchstart=begin;wheel.ontouchmove=move;window.ontouchend=end}
}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),900)}
function complete(li,mi){confetti();let levelEnd=mi===9,gameEnd=levelEnd&&li===3;if(levelEnd&&li<3)state.unlocked=Math.max(state.unlocked,li+1);save();let o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="card"><div class="big">${gameEnd?'🏆':levelEnd?'⚡':'✨'}</div><h2>${gameEnd?'Você venceu!':levelEnd?LEVELS[li].name+' concluído!':'Partida concluída!'}</h2><p>${gameEnd?'As 40 partidas foram concluídas. Você zerou o Palaviva.':levelEnd&&li<3?LEVELS[li+1].name+' foi desbloqueado.':'Pronta para a próxima?'}</p><button class="primary">${gameEnd?'Voltar ao menu':'Continuar'}</button></div>`;document.body.appendChild(o);o.querySelector('button').onclick=()=>{o.remove();if(gameEnd)return menu();if(levelEnd)return play(li+1,0);play(li,mi+1)}}
function confetti(){let c=document.createElement('div');c.className='confetti';for(let i=0;i<55;i++){let x=document.createElement('i');x.style.left=Math.random()*100+'%';x.style.setProperty('--h',Math.random()*360);x.style.setProperty('--x',(Math.random()*180-90)+'px');x.style.animationDelay=Math.random()*.4+'s';c.appendChild(x)}document.body.appendChild(c);setTimeout(()=>c.remove(),2200)}
menu();
